### ISSUE TITLE
Support Mixpanel-Swift

### ISSUE THREAD

**Issue by gmogames** [segment-integrations/analytics-ios-integration-mixpanel#23]
We use Mixpanel for our internal analytics and Segment with Mixpanel for our customer analytics (in our platform).

And we want to upgrade mixpanel to use their new Mixpanel-Swift pod instead of the old Obj-C one and I was wondering if there is any way to support using the swift library with segment (right now the spec marks the Obj-C one as a dependency)

Thanks

**Comment by f2prateek** [comment]
> use their new Mixpanel-Swift pod

Can  I ask why? I could somewhat understand if you were using Mixpanel directly, you might want the swift one so that the API is more natural (though you could still just as well use the objective c one). But since Mixpanel is "hidden" inside this integration, why does it make a difference if it uses the objective C version or the swift version internally?

**Comment by gmogames** [comment]
One, because it's based on their own recommendation, and two, since our codebase if 100% swift and we have a huge amount of analytics data being collected, we want to make sure all the new updates to swift coming in the future and to Mixpanel are in sync and we won't have issues with this.

Since they provide a swift library and recommend using it, I don't see why not use it instead of the Obj-C one.

**Comment by ladanazita** [comment]
@gmogames Is there functionality that the Mixpanel Swift library has that the Objective-C one doesn't? In addition, can you provide where Mixpanel suggests utilizing the Swift pod over the Objective-C one?

**Comment by gmogames** [comment]
https://github.com/mixpanel/mixpanel-iphone

"If you are using Swift, we recommend our Swift Library (currently supports the tracking and people API)."

**Comment by ladanazita** [comment]
@gmogames Thanks for the link. Is there functionality that the Mixpanel Swift library has that the Objective-C one doesn't? 

I'm going to open a ticket to track requests for this internally. I don't see in that link nor in Mixpanel docs on _why_ they suggest using the Swift library.

While it sounds like it would be more straightforward to have a Swift dependency in a Swift app, as far as I can tell the current state of the Mixpanel objective-C pod doesn't lack any functionality that the Swift app has. We can track this internally and reevaluate how we prioritize this as requests come in, but for now this isn't something that we will be supporting soon.

**Comment by littleStudent** [comment]
Sadly this makes the switch from mixpanel to segment a real pain for us.
Mixpanel suggests to use the swift library, so thats what people start with. Since those 2 libraries differ in their API quiet a lot, adopting segment requires a rewrite of all that mixpanel code.

**Comment by f2prateek** [comment]
Correct me if I'm wrong, but you would need a rewrite if you're migrating from Mixpanel -> Segment, regardless of whether the integration uses the Swift or Objective-C Mixpanel library.This is because the API for Mixpanel and Segment are different.

If the concern is that you need to use obejctive-C to use Segment implementation, you can actually use the Segment SDK from a Swift app. [Our tests are in Swift](https://github.com/segmentio/analytics-ios/blob/7331756df97c0417af5038bbb08ba7b4b3a0202b/AnalyticsTests/AnalyticsTests.swift#L59), and here's [another example app](https://github.com/segmentio/analytics-test-apps/blob/master/AnalyticsIOSTestApp/AnalyticsIOSTestApp/ViewController.swift). I agree the documentation could be better though, and we'll have a better Swift guide coming out soon later this year.

**Comment by f2prateek** [comment]
Got it - that makes more sense!
