### ISSUE TITLE
Legacy tags creating confusion for CocoaPods

### ISSUE THREAD

**Issue by tzm41** [segment-integrations/analytics-ios-integration-mixpanel#24]
Some older releases have version number higher than newer releases, creating confusion for CocoaPods, who thinks there is an update to the pod. It would be cool if those could be cleaned up.
<img width="602" alt="screen shot 2017-06-23 at 11 25 10 am" src="https://user-images.githubusercontent.com/5728283/27488897-ada1b20c-5806-11e7-865b-de6080d8893d.png">

**Comment by ladanazita** [comment]
@tzm41 

Thanks for bringing this up! This is definitely something we have been meaning to do. Originally, we did try to remove these legacy tags after we moved off the alpha release of analytics-ios, but Cocoapods didn't have an easy way of doing this like [they do now](https://guides.cocoapods.org/terminal/commands.html#pod_trunk_delete).

I'm going to look into the best approach here, since there is a slight chance we could be breaking some users builds by deleting these legacy tags. 

I'm going to close out the other opened issues you brought up and track this [internally](https://segment.atlassian.net/browse/EPD-3070). I will leave this issue open and update you here as I have more.

Thanks again.

**Comment by tzm41** [comment]
Thank you for investigating this!

**Comment by ladanazita** [comment]
Hi @tzm41 

Just finished deleting the [legacy Segment pods](https://github.com/CocoaPods/Specs/commits/master). I would give it some time, but this should be all good once Cocoapods has everything updated and deleted from their DBs.

The legacy tags still show up in the UI, but I will give it some time to see when the site gets rebuilt if the UI will also be updated.
![](http://g.recordit.co/KPADnn53Wd.gif)

Thanks for raising this!

**Comment by tzm41** [comment]
Great! Thanks!

**Comment by ladanazita** [comment]
Looks like Cocoapods still shows the alpha (deleted) version in the UI. Followed up [here](https://github.com/CocoaPods/cocoapods.org/issues/339)
